http:
  host: localhost
  port: 3000

db:
  mongo:
    host: localhost
    port: 27018
    username: root
    password: "123456"
    database: 501lowcode
  redis:
    host: localhost
    port: 6378
    password: "123456"
    database: 0