version: "3"
services:
  redis:
    image: redis
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6378:6379"
    command:
      - redis-server
      - /etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf:ro
      - ./redis/data:/etc/redis/data
      - ./redis/log:/etc/redis/log
  mongod:
    image: mongo
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27018:27017"
    command: --config /etc/mongo/mongod.conf
    volumes:
      - ./mongod/mongod.conf:/etc/mongo/mongod.conf
      - ./mongod/data:/data/db
      - ./mongod/log:/data/log