// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ColumnAttribute: typeof import('./src/components/node_attribute/ColumnAttribute.vue')['default']
    LeftArea: typeof import('./src/components/left_area/LeftArea.vue')['default']
    LeftAreaMenu: typeof import('./src/components/left_area/LeftAreaMenu.vue')['default']
    LibraryItem: typeof import('./src/components/component_library/LibraryItem.vue')['default']
    LibraryPanel: typeof import('./src/components/component_library/LibraryPanel.vue')['default']
    NodeAttribute: typeof import('./src/components/node_attribute/NodeAttribute.vue')['default']
    OutlineTree: typeof import('./src/components/outline_tree/OutlineTree.vue')['default']
    PageAttribute: typeof import('./src/components/node_attribute/PageAttribute.vue')['default']
    RightArea: typeof import('./src/components/right_area/RightArea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowAndColumnAttribute: typeof import('./src/components/node_attribute/RowAndColumnAttribute.vue')['default']
    RowAttribute: typeof import('./src/components/node_attribute/RowAttribute.vue')['default']
    SettingStyle: typeof import('./src/components/setting_style/SettingStyle.vue')['default']
    TopAttribute: typeof import('./src/components/node_attribute/TopAttribute.vue')['default']
  }
}
