export default {
  布局: ["UIBlock", "ElDivider"],
  基础: [
    "UIH1",
    "UIH2",
    "UIH3",
    "UIH4",
    "UIH5",
    "UIH6",
    "UIText",
    "UILink",
    "UIButton",
    "ElImage",
    "UIVideo",
  ],
  数据: [
    "ElTable",
    "ElCalendar",
    "ElAvatar",
    "UITag",
    "ElProgress",
    "ElEmpty",
    // "ElBadge",
    // "ElCard",
    // "ElCarousel",
    // "ElCollapse",
    // "ElDescriptions",
    // "ElPagination",
    // "ElResult",
    // "ElSkeleton",
    // "ElTimeline",
    // "ElTree",
    // "ElTreeSelect",
  ],
  // 导航: [
  //   "ElPageHeader",
  //   "ElMenu",
  //   "ElDropdown",
  //   "ElTabs",
  //   "ElBreadcrumb",
  //   "ElSteps",
  //   "ElBacktop",
  //   "ElAffix",
  // ],
  // 表单: [
  //   "ElInput",
  //   "ElCascader",
  //   "ElCheckbox",
  //   "ElColorPicker",
  //   "ElDatePicker",
  //   "ElForm",
  //   "ElInputNumber",
  //   "ElRadio",
  //   "ElRate",
  //   "ElSelect",
  //   "ElSlider",
  //   "ElSwitch",
  //   "ElTimePicker",
  //   "ElTimeSelect",
  //   "ElTransfer",
  //   "ElUpload",
  // ],
  // 反馈: [
  //   "ElAlert",
  //   "ElDialog",
  //   "ElDrawer",
  //   "ElLoading",
  //   "ElMessage",
  //   "ElMessageBox",
  //   "ElNotification",
  //   "ElPopConfirm",
  //   "ElPopover",
  //   "ElTooltip",
  // ],
};
